"""OpenClaw deployer — deploy OpenClaw instances on a VPS in Docker.

This service:
1. Generates a Docker Compose file for the OpenClaw stack.
2. SSHs into the target VPS and deploys the stack.
3. Returns the public URL of the running OpenClaw instance.
"""

import os
import uuid
import asyncio
import tempfile
from typing import Optional

OPENCLAW_IMAGE = os.getenv("OPENCLAW_IMAGE", "openclaw/openclaw:latest")
OPENCLAW_INTERNAL_PORT = 9000
OPENCLAW_MOCK_MODE = os.getenv("OPENCLAW_MOCK_MODE", "").lower() in ("1", "true", "yes")
HIVE_URL = os.getenv("HIVE_URL", "http://localhost:8080")


def generate_compose(
    instance_id: str,
    agent_name: str,
    agent_id: str,
    api_key: str,
    port: int = 9000,
    extra_env: Optional[dict] = None,
    config_env: Optional[dict] = None,
) -> str:
    """Return a docker-compose.yml string for an OpenClaw instance.

    extra_env: arbitrary env vars passed at deploy time (user model API keys, etc.)
    config_env: per-agent config (LLM keys, integration tokens) stored in Hive DB.
    """
    env_lines = ""
    merged = {**(extra_env or {}), **(config_env or {})}
    for k, v in merged.items():
        env_lines += f"      - {k}={v}\n"

    # Use build: . when no custom image is set (default) so we build from
    # the Dockerfile shipped to the remote dir alongside this compose file.
    if OPENCLAW_IMAGE and OPENCLAW_IMAGE != "openclaw/openclaw:latest":
        image_or_build = f"image: {OPENCLAW_IMAGE}"
    else:
        image_or_build = "build: ."

    return f"""\
# Auto-generated by Hive — OpenClaw instance {instance_id}
services:
  openclaw-{instance_id[:8]}:
    {image_or_build}
    container_name: openclaw-{instance_id[:8]}
    restart: unless-stopped
    ports:
      - "{port}:{OPENCLAW_INTERNAL_PORT}"
    environment:
      - INSTANCE_ID={instance_id}
      - AGENT_ID={agent_id}
      - AGENT_NAME={agent_name}
      - HIVE_API_KEY={api_key}
      - HIVE_URL={HIVE_URL}
{env_lines}    labels:
      hive.managed: "true"
      hive.instance-id: "{instance_id}"
      hive.agent-name: "{agent_name}"
"""


async def deploy_to_vps(
    vps_host: str,
    ssh_key_path: str,
    compose_content: str,
    instance_id: str,
    port: int,
    ssh_user: str = "root",
    ssh_port: int = 22,
) -> dict:
    """
    Deploy an OpenClaw Docker Compose stack to a remote VPS via SSH.

    Returns:
        dict with keys: success, message, url (if success)
    """
    remote_dir = f"/opt/hive/openclaw-{instance_id[:8]}"

    if OPENCLAW_MOCK_MODE:
        return {
            "success": True,
            "message": "OpenClaw deployed successfully (mock mode)",
            "url": f"http://{vps_host}:{port}",
            "remote_dir": remote_dir,
        }

    # Write compose to a temp file to scp it over
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".yml", delete=False
    ) as tmp:
        tmp.write(compose_content)
        local_compose = tmp.name

    ssh_opts = (
        f"-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "
        f"-i {ssh_key_path} -p {ssh_port}"
    )
    scp_opts = (
        f"-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "
        f"-i {ssh_key_path} -P {ssh_port}"
    )
    target = f"{ssh_user}@{vps_host}"

    # Locate the docker/ directory shipped with Hive (relative to this file).
    _svc_dir = os.path.dirname(__file__)
    _docker_dir = os.path.normpath(os.path.join(_svc_dir, "..", "..", "docker"))

    try:
        # 1. Create remote directory
        proc = await asyncio.create_subprocess_shell(
            f"ssh {ssh_opts} {target} 'mkdir -p {remote_dir}'",
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        _, stderr = await proc.communicate()
        if proc.returncode != 0:
            return {
                "success": False,
                "message": f"Failed to create remote dir: {stderr.decode()}",
            }

        # 2. Copy compose file
        proc = await asyncio.create_subprocess_shell(
            f"scp {scp_opts} {local_compose} {target}:{remote_dir}/docker-compose.yml",
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        _, stderr = await proc.communicate()
        if proc.returncode != 0:
            return {
                "success": False,
                "message": f"Failed to copy compose file: {stderr.decode()}",
            }

        # 2b. Copy Dockerfile + agent_app so the remote can do `docker build`.
        #     We always ship these — they're small and ensure the container has
        #     the correct /delegate endpoint.
        if os.path.isdir(_docker_dir):
            proc = await asyncio.create_subprocess_shell(
                f"scp {scp_opts} -r "
                f"{_docker_dir}/Dockerfile.openclaw "
                f"{_docker_dir}/agent_app "
                f"{target}:{remote_dir}/",
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            _, stderr = await proc.communicate()
            if proc.returncode != 0:
                return {
                    "success": False,
                    "message": f"Failed to copy Dockerfile: {stderr.decode()}",
                }
            # Rename Dockerfile.openclaw → Dockerfile for `docker build .`
            proc = await asyncio.create_subprocess_shell(
                f"ssh {ssh_opts} {target} "
                f"'mv {remote_dir}/Dockerfile.openclaw {remote_dir}/Dockerfile'",
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            await proc.communicate()

        # 3. Build + start container
        proc = await asyncio.create_subprocess_shell(
            f"ssh {ssh_opts} {target} "
            f"'cd {remote_dir} && docker compose build && docker compose up -d'",
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await proc.communicate()
        if proc.returncode != 0:
            return {
                "success": False,
                "message": f"docker compose up failed: {stderr.decode()}",
            }

        return {
            "success": True,
            "message": "OpenClaw deployed successfully",
            "url": f"http://{vps_host}:{port}",
            "remote_dir": remote_dir,
        }

    except Exception as e:
        return {"success": False, "message": str(e)}

    finally:
        os.unlink(local_compose)


async def teardown_on_vps(
    vps_host: str,
    ssh_key_path: str,
    instance_id: str,
    ssh_user: str = "root",
    ssh_port: int = 22,
) -> dict:
    """Tear down (stop + remove) an OpenClaw instance on a remote VPS."""
    remote_dir = f"/opt/hive/openclaw-{instance_id[:8]}"
    ssh_opts = (
        f"-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "
        f"-i {ssh_key_path} -p {ssh_port}"
    )
    target = f"{ssh_user}@{vps_host}"

    try:
        proc = await asyncio.create_subprocess_shell(
            f"ssh {ssh_opts} {target} "
            f"'cd {remote_dir} && docker compose down -v && rm -rf {remote_dir}'",
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        _, stderr = await proc.communicate()
        if proc.returncode != 0:
            return {"success": False, "message": stderr.decode()}
        return {"success": True, "message": "OpenClaw instance removed"}
    except Exception as e:
        return {"success": False, "message": str(e)}


async def update_container_env(
    vps_host: str,
    ssh_key_path: str,
    instance_id: str,
    agent_name: str,
    agent_id: str,
    api_key: str,
    port: int,
    config_env: dict,
    ssh_user: str = "root",
    ssh_port: int = 22,
) -> dict:
    """
    Update a running OpenClaw instance with new env vars (e.g. LLM keys,
    integration tokens). Generates a new compose file and force-recreates
    the container.
    """
    if OPENCLAW_MOCK_MODE:
        return {"success": True, "message": "Container reconfigured (mock mode)"}

    compose = generate_compose(
        instance_id=instance_id,
        agent_name=agent_name,
        agent_id=agent_id,
        api_key=api_key,
        port=port,
        config_env=config_env,
    )

    remote_dir = f"/opt/hive/openclaw-{instance_id[:8]}"
    ssh_opts = (
        f"-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "
        f"-i {ssh_key_path} -p {ssh_port}"
    )
    scp_opts = (
        f"-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "
        f"-i {ssh_key_path} -P {ssh_port}"
    )
    target = f"{ssh_user}@{vps_host}"

    with tempfile.NamedTemporaryFile(mode="w", suffix=".yml", delete=False) as tmp:
        tmp.write(compose)
        local_compose = tmp.name

    try:
        # Copy updated compose file
        proc = await asyncio.create_subprocess_shell(
            f"scp {scp_opts} {local_compose} {target}:{remote_dir}/docker-compose.yml",
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        _, stderr = await proc.communicate()
        if proc.returncode != 0:
            return {"success": False, "message": f"scp failed: {stderr.decode()}"}

        # Force-recreate container with new env
        proc = await asyncio.create_subprocess_shell(
            f"ssh {ssh_opts} {target} "
            f"'cd {remote_dir} && docker compose up -d --force-recreate'",
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        _, stderr = await proc.communicate()
        if proc.returncode != 0:
            return {"success": False, "message": f"docker compose up failed: {stderr.decode()}"}

        return {"success": True, "message": "Container reconfigured and restarted"}
    except Exception as e:
        return {"success": False, "message": str(e)}
    finally:
        os.unlink(local_compose)
